# Generated by Django 5.0.1 on 2024-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_remove_producto_cantidad_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(max_length=30),
        ),
    ]
