# Generated by Django 5.0.1 on 2024-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_producto_talle_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajarNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('curriculum', models.FileField(upload_to='archivos/')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
