# Generated by Django 5.0.1 on 2024-02-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_trabajarnosotros_alter_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrabajarNosotros',
        ),
        migrations.AddField(
            model_name='pago',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='Clientes.sucursal'),
        ),
    ]
