# Generated by Django 5.0.1 on 2024-02-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_delete_trabajarnosotros_pago_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='accesorios/')),
                ('precio', models.FloatField()),
            ],
        ),
    ]
